version: '3'

# Command-line
# https://docs.docker.com/compose/reference/

services:
  php:
    build: .
    container_name: fullstack-laravel-relay-php
    ports:
      - 8000:80
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/apache2/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./packages/api:/var/www/html
    depends_on:
      - mysqldb
  php-2:
    build: .
    container_name: fullstack-laravel-relay-php-2
    ports:
      - 8020:80
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/apache2/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./packages/api-2:/var/www/html
    depends_on:
      - mysqldb
  myadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: fullstack-laravel-relay-phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=fullstack-laravel-relay-mysql
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7.21
    container_name: fullstack-laravel-relay-mysql
    restart: always
    env_file:
     - .env
     - ./packages/api/.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql_data:/var/lib/mysql